timestamp: "2025-04-18T04:30:00.000Z"
computer: "DE-Windows-01"

process_guid: "{11111111-2222-3333-4444-555555555555}"
process_id: "4321"
image: "C:\\Windows\\System32\\powershell.exe"

protocol: "tcp"
initiated: "true"

source_ip: "192.168.1.50"
source_port: "49675"
source_hostname: "DE-Windows-01"

destination_ip: "1.3.3.7"
destination_port: "443"
destination_hostname: "ItsEvilWhenThereAreNoTacosLeft.com"
user: "TommyBoy"
domain: "deathgroup-labs"
